apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # اولویت ۱: اگر آدرس /parse بود -> برو سرویس پایتون
      - path: /parse
        pathType: Prefix
        backend:
          service:
            name: parser-service
            port:
              number: 5000

      - path: /history
        pathType: Prefix
        backend:
          service:
            name: parser-service
            port:
              number: 5000
      # اولویت ۲: هر چیز دیگری بود (/) -> برو سرویس فرانت‌ند
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80